spring:
  application:
    name: everence
  datasource:
    url: jdbc:postgresql://localhost:5432/everence

    username: ${USER}
    password: ${PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:

  secret: ${JWT_SECRET}
  expiration: 3600000

server:
  port: 8080
  ssl:
    key-store-type: JKS
    key-store: classpath:server.jks
    key-store-password: ${SERVERPASS}
    key-alias: server